# Generated by Django 4.0.4 on 2022-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Hello', max_length=120),
            preserve_default=False,
        ),
    ]
